### ISSUE TITLE
Implementing data API

### ISSUE THREAD

**Issue by jiyolla** [Remian103/lolskin-price-tracker#10]
In the last meeting, we've discussed the API between frontend and backend.

This is the original draft.
![image](https://user-images.githubusercontent.com/71974321/128871433-3275fa20-3a8f-4ff5-8e52-6cdf1132c676.png)

I've made a little changes in endpoints in an attempt to follow some common REST API design practice.
The proposed endpoints are in red font.

어떻게 생각해

I've created the champion one.
You can check it in the latest pull request.

**Comment by Remian103** [comment]
pull request #11 은  main 에 merge 했습니다.
추가 api 구현 시에는 여기에 계속 업데이트하는 게 좋을까요,
아니면 따로 이슈를 파서 하는게 좋을까요?

**Comment by jiyolla** [comment]
> pull request #11 은 main 에 merge 했습니다.
> 추가 api 구현 시에는 여기에 계속 업데이트하는 게 좋을까요,
> 아니면 따로 이슈를 파서 하는게 좋을까요?

원래는 여기를 계속 참조해서 업데이트할 예정이었는데,
각 기능마다 본 이슈를 참고로 하는 하위(관련된) 이슈를 만들어서 각 기능에 구체적인 토의를 하고 PR를 연결하는 것도 좋겠네요

**Comment by jiyolla** [comment]
API described in this issue is all implemented and their documentation is now available 24/7 on remote server.
Closing.
