### ISSUE TITLE
Site design

### ISSUE THREAD

**Issue by Remian103** [Remian103/lolskin-price-tracker#34]
Nightly version of design has uploaded in 'frontend-design' branch.
If you want to test new design, please check that branch.

**Comment by jiyolla** [comment]
챔프 위에 마우스 올렸을 때 그 누를 수는 마우스 모양으로 바뀌면 좋을 듯

**Comment by Remian103** [comment]
> 챔프 위에 마우스 올렸을 때 그 누를 수 있는 마우스 모양으로 바뀌면 좋을 듯

successfully applied in dev

**Comment by jiyolla** [comment]
> > 챔프 위에 마우스 올렸을 때 그 누를 수 있는 마우스 모양으로 바뀌면 좋을 듯
> 
> successfully applied in dev

Great.

그 챔프 눌렀을 때 스킨 나열하는 것과, 스킨에서 다른 스킨을 나열할 때,
첫 스킨을 왼쪽에 붙이는 거 어떻게 생각함? 지금은 첫 스킨이 중앙에 위치함.

**Comment by Remian103** [comment]
> 그 챔프 눌렀을 때 스킨 나열하는 것과, 스킨에서 다른 스킨을 나열할 때,
> 첫 스킨을 왼쪽에 붙이는 거 어떻게 생각함? 지금은 첫 스킨이 중앙에 위치함.

applied in dev

**Comment by jiyolla** [comment]
> > 그 챔프 눌렀을 때 스킨 나열하는 것과, 스킨에서 다른 스킨을 나열할 때,
> > 첫 스킨을 왼쪽에 붙이는 거 어떻게 생각함? 지금은 첫 스킨이 중앙에 위치함.
> 
> applied in dev

hmm...
The original design was not that bad, but just looking a little bit awkward. But it did seem intended, so I was kind of expecting some motivation(e.g. referencing some good looking site) behind that design when I suggested left aligning.

If you are ok with left aligning, that's good.

**Comment by Remian103** [comment]
> But it did seem intended, so I was kind of expecting some motivation(e.g. referencing some good looking site) behind that design when I suggested left aligning.

The original one is just initial design of carousel package :) Keep Suggesting! It's really helpful to improve our design!

**Comment by jiyolla** [comment]
> > But it did seem intended, so I was kind of expecting some motivation(e.g. referencing some good looking site) behind that design when I suggested left aligning.
> 
> The original one is just initial design of carousel package :) Keep Suggesting! It's really helpful to improve our design!

좋아용

**Comment by Remian103** [comment]
### Discussion tab is open!
#40 will cover this topic
