### ISSUE TITLE
Determining UI/UX

### ISSUE THREAD

**Issue by jiyolla** [Remian103/lolskin-price-tracker#5]
- [x] Meeting for brainstorming.
 - [x] Remian103 post frontend template candidates.
 - [x] Follow up meeting for fixing the template.

**Comment by Remian103** [comment]
>**Considerations..**

- component's default design
- documentation
- plenty of examples

>**Candidates**

1. https://next.material-ui.com/
  document : [link](https://material-ui.com/versions/)
  most papular
2. https://atomizecode.com/
  document : [link](https://atomizecode.com/docs/react/intro)
3. https://www.creative-tim.com/product/argon-design-system-react/
  document : [link](https://demos.creative-tim.com/argon-design-system-react/?_ga=2.67346833.1005691174.1627878309-1751991792.1627878309#/documentation/overview)
  demo-page : [link](https://demos.creative-tim.com/argon-design-system-react/?_ga=2.67346833.1005691174.1627878309-1751991792.1627878309#/)

**Comment by jiyolla** [comment]
I've tried to do a little bit study on react frameworks/libraries.

Most "best react ui framework/libraries in 2021" posts are just simply listing the available choices without giving a pros and cons of so many choices.
But I do see that the material ui is the most popular one.

So, if there aren't many differences? Maybe we can just go with the most popular one.
그냥 디자인 차이인가?

**Comment by Remian103** [comment]
일단 기본 디자인은 atomizecode 로 하되 변동사항이나 추가사항이 생기면 그때그때 언급하는걸로 하겠습니다.

**Comment by jiyolla** [comment]
그럼 추가사항 생길 때 다시 open하도록 하죠.
