### ISSUE TITLE
Implement Comment API

### ISSUE THREAD

**Issue by jiyolla** [Remian103/lolskin-price-tracker#57]
### The first decision we have to make: Which URI should the comment api startwith?
```
- /api/comments/
```
  or
```
- /api/skins/{skin_id}/comments/
```

Regarding this issue, I found some related SO questions.
https://stackoverflow.com/questions/15259843/how-to-structure-rest-resource-hierarchy
https://stackoverflow.com/questions/2150171/how-should-a-rest-url-schema-look-like-for-a-tree-hierarchy
https://stackoverflow.com/questions/25872501/restful-flat-hierarchy-vs-dynamic-hierarchy-for-search-resource

This seems not be a problem of RESTful or not. Rather it's just a choice of URI design. It's even ok to have both at the same time.
But I see more people suggesting the first one, because it's simpler.
The rationale behind the second one is being explicit on the relationship between 'skins' and 'comments', but by doing so it is also repeating some information. The exposure of db structure which might not be bad but it really it not necessary as well. 

I would also like to go with first one, but I'm also open to opinions.

### Second, regarding the use of PUT/DELETE method
In the above mentioned SO questions, actually some posts are already mentioning the usage of put/delete method to interact with the resource pointing out that these practices are more related to being RESTful or not.

There are many other introductory posts on how to follow RESTful design practice, like
https://medium.com/hashmapinc/rest-good-practices-for-api-design-881439796dc9

The usage of put/delete seems recommended.

### So with above assumptions, I have come up with comment api draft like
1. Post new a comment
`POST /api/skins/{skin_id}/comments`
2. Get a single comment
`GET /api/comments/{comment_id}`
3. Modify a comment
`PUT /api/comments/{comment_id}`
4. Delete a comment
`DELETE /api/comments/{comment_id}`
5. Like a comment
`POST /api/comments/{comment_id}/like`
6. Unlike a comment
`DELETE /api/comments/{comment_id}/like`
7. Dislike a comment
`POST /api/comments/{comment_id}/dislike`
8. Undislike a comment
`DELETE /api/comments/{comment_id}/dislike`
9. Get the comment 'list' of a skin
`GET /api/skins/{skin_id}/comments?skip={starting_index}&limit={maximum_last_index}&order_by={method_of_ordering}`

Note that 1, 9 use URLs that are under 'skins' hierarchy, because those are the ones actually need the 'skin_id'.

And two schemas
1. Comments List: An object about a list of a comment. Specifically and currently, this list is curated by the skin_id and index.
```
Comments List: {
  skin_id: int
  num_comments: int
  starting_index: int
  last_index: int
  order_by: str
  comments: List[Comment]
  other possible data about the 'list'(e.g. Highest likes, Total likes, Last comment date, etc)
}
```

2. Comment: An object about a comment
```
Comment: {
  comment_id: int
  skin_id: int
  author_username: str
  content: str
  created: datetime
  last_modified: datetime
  likes: int
  dislikes: int
}
```
Upon the list of users who liked and disliked, I'm not sure whether it should be a property of 'Comment' or should there be a special api for that. Or is this 'list' actually needed?

**Comment by jiyolla** [comment]
Some endpoints need more clarification(like authentication in request,content of response, etc)

**Comment by Remian103** [comment]
expected response from a front-end perspective
1. if successful, comment_id
2. 'comment'
3. if successful
4. if successful
5. {if successful, 'comment' or current number of likes for updating }
6.  same as **5**
7.  same as **5**
8.  same as **5**
9.  { number of requested comments, number of total comments, ['comment'] } 



in response **1, 3, 4**, there are some possible way to update comment list
1. if success, then reqeust **9** (fully refresh)
2. or reqeust **2** and then add comment in comment list
   (when you want to see other user's new comment, refresh page)
3. or add 'comment' in responses
4. or generate and add 'comment' in frontend by form data and comment_id (not recommend.. have potential of side effect..)

**Comment by Remian103** [comment]
>Upon the list of users who liked and disliked, I'm not sure whether it should be a property of 'Comment' or should there be a special api for that. Or is this 'list' actually needed?

In frontend, likes button appear differently depending on whether the user cliked it or not.
User list in comment will help to determine the appearance of likes button.
for example, when Log-in User does not exit in the user list, likes button will be activated

**Comment by jiyolla** [comment]
> in response **1, 3**, there are some possible way to update comment list
> 
> 1. if success, then reqeust **9** (fully refresh)
> 2. or reqeust **2** and then add comment in comment list
>    (when you want to see other user's new comment, refresh page)
> 3. or add 'comment' in responses
> 4. or generate and add 'comment' in frontend by form data and comment_id (not recommend.. have potential of side effect..)

3 would be great. It seems to be a common approach.
And about the new comment by the user, it also seems ok to put them in the top of the comment list(like YouTube comment), so there's no sorting problem.


> in response **4**, there are some possible way to update comment list
> 
> 1. if success, then reqeust **9** (fully refresh)
> 2. or delete comment from list (not refresh)

I'd think 2 is better, but I have no strong opinions.

**Comment by jiyolla** [comment]
> > Upon the list of users who liked and disliked, I'm not sure whether it should be a property of 'Comment' or should there be a special api for that. Or is this 'list' actually needed?
> 
> In frontend, likes button appear differently depending on whether the user cliked it or not.
> User list in comment will help to determine the appearance of likes button.
> for example, when Log-in User does not exist in the user list, likes button will be activated

That's a point.

What about having the 'what I liked list' in user.

Where there's a another api that provide some data about the user(like his username, what he liked/disliked, comments he wrote , and possibly some features(favorite skins, notifications...))

So after the login the app just call user api once to get them.

This way, checking whether current user liked/disliked is more efficient and also more extensible.

**Comment by Remian103** [comment]
I'm not sure that checking a list of user's comments is more efficient than checking a list of users in comment...
Could you explain some detail about it...?
or Is there any performance issue in database?

On second thought, both way may not be good..
Instead, how about putting user_id in request?
Then, back-end server will take calculations whether like or not.
In this case, response will be free from a large amount of list data..

**Comment by jiyolla** [comment]
> I'm not sure that checking a list of user's comments is more efficient than checking a list of users in comment...
> Could you explain some detail about it...?
> or Is there any performance issue in database?

Ah, you're right.

> On second thought, both way may not be good..
> Instead, how about putting user_id in request?
> Then, back-end server will take calculations whether like or not.
> When I looked up some pages related like function, they set up separate like table,
> and when api requested, inform like state directly to front-end.
> In this case, response will be free from a large amount of list data..

Is that something like, for example, an api that receives a list of comment and the user id then returns the true/false(maybe 3 states like/dislike/neither) table?

**Comment by Remian103** [comment]
A seperate api that recieves a list of comment id and user id is good, or api 9 seems to be able to do this together.

9. Get the comment 'list' of a skin
  `GET /api/skins/{skin_id}/comments?skip={starting_index}&limit={maximum_last_index}&order_by={method_of_ordering}&username={username}`
  response : comment list with comments like below
```
Comment: {
  comment_id: int
  skin_id: int
  author_username: str
  content: str
  created: datetime
  last_modified: datetime
  likes: int
  dislikes: int
  like_state : bool
}
````
when username is null, like_state always false.

**Comment by jiyolla** [comment]
> A seperate api that recieves a list of comment id and user id is good, or api 9 seems to be able to do this together.
> 
> 1. Get the comment 'list' of a skin
>    `GET /api/skins/{skin_id}/comments?skip={starting_index}&limit={maximum_last_index}&order_by={method_of_ordering}&username={username}`
>    response : comment list with comments like below
> 
> ```
> Comment: {
>   comment_id: int
>   skin_id: int
>   author_username: str
>   content: str
>   created: datetime
>   last_modified: datetime
>   likes: int
>   dislikes: int
>   like_state : bool
> }
> ```
> 
> when username is null, like_state always false.

Great.
Instead of username, maybe we should use the same id_token. Cause 'did someone like it' could be considered private.

And we modify 'Comment' schema
and for requests #2&9(they were the only two didn't required authentication), the id_token is optional, if provided, set the like_state(s).

**Comment by jiyolla** [comment]
## Update
> some more details
> 
> ### Authentication
> Only 2,9 are available without login
> Others require authentication, which would probably be a google's id_token(google.oauth2.id_token).
> 
> return 401 when it's invalid
> 
> ### Responses(other than is successful)
> 1: if successful, comment_id
> 2: 'Comment'
> 9: 'Commens List'

### Request
All requests: "Authorization: Bearer <id_token>" in header. For 2&9 it's optional(to set like/dislike state in 'Comment').
1&3: content: str

### Response
1&3: Created 'Comment'
2: 'Comment'
5-6: likes: int
7-8: dislikes: int
9: 'Comment List'

> 2. Comment: An object about a comment
> ```
> Comment: {
>   comment_id: int
>   skin_id: int
>   author_username: str
>   content: str
>   created: datetime
>   last_modified: datetime
>   likes: int
>   dislikes: int
> }
> ```

2. Comment: An object about a comment
```
Comment: {
  comment_id: int
  skin_id: int
  author_username: str
  content: str
  created: datetime
  last_modified: datetime
  likes: int
  dislikes: int
  like_state: bool          # False if id_token not provided
  dislike_state: bool       # False if id_token not provided 
}
```

**Comment by jiyolla** [comment]
## Update on Sep. 16th

### Methods list
1. Post new a comment
`POST /api/skins/{skin_id}/comments`
2. Get a single comment
`GET /api/comments/{comment_id}`
3. Modify a comment
`PUT /api/comments/{comment_id}`
4. Delete a comment
`DELETE /api/comments/{comment_id}`
5. Like a comment
`POST /api/comments/{comment_id}/likes`
6. Unlike a comment
`DELETE /api/comments/{comment_id}/likes`
7. Dislike a comment
`POST /api/comments/{comment_id}/dislikes`
8. Undislike a comment
`DELETE /api/comments/{comment_id}/dislikes`
9. Get the comment 'list' of a skin
`GET /api/skins/{skin_id}/comments?skip={starting_index}&limit={last_index+1}&order_by={method_of_ordering}`

### Request data
1~9: "Authorization: Bearer <id_token>" in header. For 2&9 it's optional(to set 'current_user_auth' in 'Comment').
1&3: { "content": "str"}

### Response data
1&3: Created 'Comment'
2: 'Comment'
5-6: likes: int
7-8: dislikes: int
9: 'Comment List'

### Schemas
```
Comment: {
  skin_id: int
  author_username: str
  id: int
  content: str
  created: datetime
  last_modified: datetime
  likes: int
  dislikes: int
  current_user_auth: { # Null if no token is provided
    is_modifiable: bool
    like_state: bool
    dislike_state: bool
  }
}
```

```
Comments List: {
  skin_id: int
  num_comments: int
  limit: int
  skip: int
  order_by: str
  comments: List[Comment]
}
```

**Comment by jiyolla** [comment]
## Database
- [ ] Comment id should follow 'skin_id' + 'comment_uid'
  e.g. 1001 000001.
  This is the scheme used by the Riot on champions and skin id allocation.
  It's good to be consistent.
  And probably, instead of autoincrement(which could possibly reuse the comment id of deleted ones).
