### ISSUE TITLE
프론트엔드 개발환경 구성 (Docker)

### ISSUE THREAD

**Issue by Remian103** [Remian103/lolskin-price-tracker#8]
docker container를 활용한 개발환경 구성

- [x] dockerfile을 통해 필요한 dependency들이 구성된 docker image 생성
- [x] docker container 실행 시 source code 부분을 마운트하여 로컬 환경에서 파일 수정시 container에 반영되도록 할 것
- [x] 위 과정을 스크립트화

**Comment by jiyolla** [comment]
:+1::heart::+1:

**Comment by jiyolla** [comment]
실수로 close누른듯

**Comment by Remian103** [comment]
추가 변동 사항 생기기 전까지는 close
